version: '2'

services:
 db:
  image: mysql:latest
  container_name: mysql
  volumes:
    - db_data:/var/lib/mysql
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: admin
   MYSQL_DATABASE: admin
   MYSQL_USER: admin
   MYSQL_PASSWORD: admin

 phpmyadmin:
  depends_on:
   - db
  image: phpmyadmin/phpmyadmin:latest
  container_name: phpmyadmin
  volumes:
   - www:/var/www/html
  ports:
   - "801:80"
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: admin
   MYSQL_USER: admin
   MYSQL_PASSWORD: admin
   PMA_ARBITRARY: db:3306

 apache:
  image: eboraas/apache-php
  container_name: apache
  volumes:
   - /var/www/html:/var/www/html
  ports:
   - "80:80"
   - "443:443"
  restart: always
volumes:
 db_data:
 www:

